export interface GameMeta {
  id: string
  title: string
  genre: string
  description: string
  controls: Record<string, string>
  href: string
}

export const GAMES_CATALOG: Record<string, GameMeta> = {
  flappy: {
    id: "flappy",
    title: "Flappy Bird 3D",
    genre: "3D Cartoon Arcade Flight",
    description: "Classic arcade flight with real-time wing flaps, multi-skin bird picker, warp pipe collisions, and cloud horizon.",
    controls: { "Space / Click": "Flap Wings", "P": "Pause" },
    href: "/games/flappy-engine/",
  },
  flappyEngine: {
    id: "flappyEngine",
    title: "Flappy Bird 3D",
    genre: "3D Cartoon Arcade Flight",
    description: "Classic arcade flight with real-time wing flaps, multi-skin bird picker, warp pipe collisions, and cloud horizon.",
    controls: { "Space / Click": "Flap Wings", "P": "Pause" },
    href: "/games/flappy-engine/",
  },
  knightfall: {
    id: "knightfall",
    title: "Knightfall: Gotham Flight",
    genre: "Superhero Flight Simulator",
    description: "Glide across a stormy gothic city, dive-bomb from skyscrapers, deploy the bat-signal, dodge blimps, and hit landing pads.",
    controls: { "A / D": "Bank Turn", "W / S": "Pitch", "Shift": "Dive Bomb", "Esc": "Pause" },
    href: "/games/knightfall-engine/",
  },
  knightfallEngine: {
    id: "knightfallEngine",
    title: "Knightfall: Gotham Flight",
    genre: "Superhero Flight Simulator",
    description: "Glide across a stormy gothic city, dive-bomb from skyscrapers, deploy the bat-signal, dodge blimps, and hit landing pads.",
    controls: { "A / D": "Bank Turn", "W / S": "Pitch", "Shift": "Dive Bomb", "Esc": "Pause" },
    href: "/games/knightfall-engine/",
  },
  smash: {
    id: "smash",
    title: "Kirby Smash Arena",
    genre: "1v1 Arena Platform Brawler",
    description: "Battle with Mario, Kirby, Samus & DK on floating arenas with knockback physics, AI bots, combat combos & stage select.",
    controls: { "A / D": "Move", "W": "Jump", "J": "Jab Attack", "K": "Special Attack" },
    href: "/games/kirby-smash-engine/",
  },
  smashEngine: {
    id: "smashEngine",
    title: "Kirby Smash Arena",
    genre: "1v1 Arena Platform Brawler",
    description: "Battle with Mario, Kirby, Samus & DK on floating arenas with knockback physics, AI bots, combat combos & stage select.",
    controls: { "A / D": "Move", "W": "Jump", "J": "Jab Attack", "K": "Special Attack" },
    href: "/games/kirby-smash-engine/",
  },
  mossbound: {
    id: "mossbound",
    title: "Mossbound: Enchanted Grove",
    genre: "3D First-Person Action RPG",
    description: "Complete dark fantasy melee game with rune swords, 5 creature waves, Thornheart boss, tactical minimap, stamina & upgrades.",
    controls: { "WASD": "Move", "Mouse": "Look / Slash", "Shift": "Sprint", "E": "Grove Blast" },
    href: "/games/mossbound-engine/",
  },
  mossboundEngine: {
    id: "mossboundEngine",
    title: "Mossbound: Enchanted Grove",
    genre: "3D First-Person Action RPG",
    description: "Complete dark fantasy melee game with rune swords, 5 creature waves, Thornheart boss, tactical minimap, stamina & upgrades.",
    controls: { "WASD": "Move", "Mouse": "Look / Slash", "Shift": "Sprint", "E": "Grove Blast" },
    href: "/games/mossbound-engine/",
  },
  parking: {
    id: "parking",
    title: "Perfect Parking 3D",
    genre: "Vehicle Physics & Driving",
    description: "Drive sports cars through parking obstacle courses with realistic vehicle physics, tire traction, and timing challenges.",
    controls: { "W / Up": "Throttle", "S / Down": "Brake/Reverse", "A / D": "Steer", "R": "Restart" },
    href: "/games/parking-engine/",
  },
  parkingEngine: {
    id: "parkingEngine",
    title: "Perfect Parking 3D",
    genre: "Vehicle Physics & Driving",
    description: "Drive sports cars through parking obstacle courses with realistic vehicle physics, tire traction, and timing challenges.",
    controls: { "W / Up": "Throttle", "S / Down": "Brake/Reverse", "A / D": "Steer", "R": "Restart" },
    href: "/games/parking-engine/",
  },
  boat: {
    id: "boat",
    title: "Tiny Boat Docking",
    genre: "Marina Boat Simulator",
    description: "Pilot speedboats through marinas, dynamic water buoyancy waves, wake spray, slip docking & scoring.",
    controls: { "WASD / Arrows": "Throttle & Rudder", "Space": "Reverse Brake", "R": "Retry" },
    href: "/games/boat-engine/",
  },
  boatEngine: {
    id: "boatEngine",
    title: "Tiny Boat Docking",
    genre: "Marina Boat Simulator",
    description: "Pilot speedboats through marinas, dynamic water buoyancy waves, wake spray, slip docking & scoring.",
    controls: { "WASD / Arrows": "Throttle & Rudder", "Space": "Reverse Brake", "R": "Retry" },
    href: "/games/boat-engine/",
  },
  mars: {
    id: "mars",
    title: "The Mars Trail",
    genre: "Sci-Fi Planetary Space Flight",
    description: "Pilot Martian spacecraft through retro pixel-shaded canyons, manage supplies, avoid hazards, and reach Olympus Mons.",
    controls: { "WASD / Arrows": "Steer Craft", "Space": "Boost", "Esc": "Menu" },
    href: "/games/mars-engine/",
  },
  marsEngine: {
    id: "marsEngine",
    title: "The Mars Trail",
    genre: "Sci-Fi Planetary Space Flight",
    description: "Pilot Martian spacecraft through retro pixel-shaded canyons, manage supplies, avoid hazards, and reach Olympus Mons.",
    controls: { "WASD / Arrows": "Steer Craft", "Space": "Boost", "Esc": "Menu" },
    href: "/games/mars-engine/",
  },
  hoops: {
    id: "hoops",
    title: "Hoops Shootout 3D",
    genre: "3D Basketball Arcade",
    description: "Shoot hoops with authentic ball physics, shot charge aiming, swish multipliers, net dynamics, and buzzer beaters.",
    controls: { "Mouse Drag / Touch": "Charge & Aim Power", "Release": "Shoot Ball", "Esc": "Pause" },
    href: "/games/hoops-engine/",
  },
  hoopsEngine: {
    id: "hoopsEngine",
    title: "Hoops Shootout 3D",
    genre: "3D Basketball Arcade",
    description: "Shoot hoops with authentic ball physics, shot charge aiming, swish multipliers, net dynamics, and buzzer beaters.",
    controls: { "Mouse Drag / Touch": "Charge & Aim Power", "Release": "Shoot Ball", "Esc": "Pause" },
    href: "/games/hoops-engine/",
  },
  lawn: {
    id: "lawn",
    title: "Lawn Mowing Simulator",
    genre: "3D Yard Mower Simulator",
    description: "Ride mowers across grassy suburban yards, slice real-time blades of grass, avoid flowerbeds, and achieve 100% manicured lawns.",
    controls: { "WASD / Arrows": "Drive Mower", "Space": "Handbrake", "C": "Change Camera" },
    href: "/games/lawn-engine/",
  },
  lawnEngine: {
    id: "lawnEngine",
    title: "Lawn Mowing Simulator",
    genre: "3D Yard Mower Simulator",
    description: "Ride mowers across grassy suburban yards, slice real-time blades of grass, avoid flowerbeds, and achieve 100% manicured lawns.",
    controls: { "WASD / Arrows": "Drive Mower", "Space": "Handbrake", "C": "Change Camera" },
    href: "/games/lawn-engine/",
  },
  blaster: {
    id: "blaster",
    title: "Battle Blaster Workbench",
    genre: "3D Sci-Fi Weapon Customizer",
    description: "Inspect, customize, and test-fire futuristic energy blasters with modular attachments, finishes, audio SFX, and inspect animations.",
    controls: { "Left Click / Drag": "Orbit Inspect", "F": "Inspect Weapon", "Click Modules": "Equip / Swap" },
    href: "/games/blaster-engine/",
  },
  blasterEngine: {
    id: "blasterEngine",
    title: "Battle Blaster Workbench",
    genre: "3D Sci-Fi Weapon Customizer",
    description: "Inspect, customize, and test-fire futuristic energy blasters with modular attachments, finishes, audio SFX, and inspect animations.",
    controls: { "Left Click / Drag": "Orbit Inspect", "F": "Inspect Weapon", "Click Modules": "Equip / Swap" },
    href: "/games/blaster-engine/",
  },
  boulder: {
    id: "boulder",
    title: "Boulder Cove",
    genre: "Prehistoric Island Life Simulation",
    description: "Paddle up to Boulder Cove, shake fruit trees, fish ripples, net dragonflies, return lost eggs, and build your boulder hut.",
    controls: { "WASD": "Move", "Space": "Action / Cast / Swing", "Touch": "On-screen Controls" },
    href: "/games/boulder-engine/",
  },
  boulderEngine: {
    id: "boulderEngine",
    title: "Boulder Cove",
    genre: "Prehistoric Island Life Simulation",
    description: "Paddle up to Boulder Cove, shake fruit trees, fish ripples, net dragonflies, return lost eggs, and build your boulder hut.",
    controls: { "WASD": "Move", "Space": "Action / Cast / Swing", "Touch": "On-screen Controls" },
    href: "/games/boulder-engine/",
  },
  experiment: {
    id: "experiment",
    title: "The Forgotten Experiment",
    genre: "3D Sci-Fi Escape Room",
    description: "Wake up in a classified containment facility, inspect consoles, solve cryptographic locks, and escape the laboratory.",
    controls: { "Mouse Drag": "Look", "Left Click": "Examine / Interact", "WASD": "Walk", "Esc": "Menu" },
    href: "/games/experiment-engine/",
  },
  experimentEngine: {
    id: "experimentEngine",
    title: "The Forgotten Experiment",
    genre: "3D Sci-Fi Escape Room",
    description: "Wake up in a classified containment facility, inspect consoles, solve cryptographic locks, and escape the laboratory.",
    controls: { "Mouse Drag": "Look", "Left Click": "Examine / Interact", "WASD": "Walk", "Esc": "Menu" },
    href: "/games/experiment-engine/",
  },
  reef: {
    id: "reef",
    title: "Reef Rivals: Treasure Tide",
    genre: "Tropical Slingshot Artillery Combat",
    description: "Battle pirate crews across tropical reefs, aim coconut and pineapple artillery, collect golden shells, and unlock rival characters.",
    controls: { "Sliders": "Aim Angle & Power", "Space / Button": "Fire Artillery" },
    href: "/games/reef-engine/",
  },
  reefEngine: {
    id: "reefEngine",
    title: "Reef Rivals: Treasure Tide",
    genre: "Tropical Slingshot Artillery Combat",
    description: "Battle pirate crews across tropical reefs, aim coconut and pineapple artillery, collect golden shells, and unlock rival characters.",
    controls: { "Sliders": "Aim Angle & Power", "Space / Button": "Fire Artillery" },
    href: "/games/reef-engine/",
  },
  swimming: {
    id: "swimming",
    title: "Just Keep Swimming",
    genre: "Endless 3D Ocean Drift",
    description: "Thread bubble rings, bounce off glowing bells, dodge stinging tentacles, and boost through endless underwater drifts.",
    controls: { "WASD": "Steer", "Shift": "Boost", "Esc": "Pause" },
    href: "/games/swimming-engine/",
  },
  swimmingEngine: {
    id: "swimmingEngine",
    title: "Just Keep Swimming",
    genre: "Endless 3D Ocean Drift",
    description: "Thread bubble rings, bounce off glowing bells, dodge stinging tentacles, and boost through endless underwater drifts.",
    controls: { "WASD": "Steer", "Shift": "Boost", "Esc": "Pause" },
    href: "/games/swimming-engine/",
  },
  breakline: {
    id: "breakline",
    title: "Breakline",
    genre: "Downhill Snowboard Chase",
    description: "Outrun the whiteout on alpine slopes, carve turns, chain grinds and aerial flips, and evade pursuing predators.",
    controls: { "A / D": "Carve", "Shift": "Tuck", "Space": "Ollie", "Q / E": "Spin", "Z / X": "Flip", "G / H": "Grab" },
    href: "/games/breakline-engine/",
  },
  breaklineEngine: {
    id: "breaklineEngine",
    title: "Breakline",
    genre: "Downhill Snowboard Chase",
    description: "Outrun the whiteout on alpine slopes, carve turns, chain grinds and aerial flips, and evade pursuing predators.",
    controls: { "A / D": "Carve", "Shift": "Tuck", "Space": "Ollie", "Q / E": "Spin", "Z / X": "Flip", "G / H": "Grab" },
    href: "/games/breakline-engine/",
  },
  vanguard: {
    id: "vanguard",
    title: "Vanguard Protocol",
    genre: "Cinematic Sci-Fi Combatant Selector",
    description: "Inspect futuristic combatants in a 3D hologram bay with signature combat animations, inspect zoom, and tactical stats.",
    controls: { "Left / Right": "Select Combatant", "Mouse Drag": "Orbit Inspect", "Pinch / Scroll": "Zoom" },
    href: "/games/vanguard-engine/",
  },
  vanguardEngine: {
    id: "vanguardEngine",
    title: "Vanguard Protocol",
    genre: "Cinematic Sci-Fi Combatant Selector",
    description: "Inspect futuristic combatants in a 3D hologram bay with signature combat animations, inspect zoom, and tactical stats.",
    controls: { "Left / Right": "Select Combatant", "Mouse Drag": "Orbit Inspect", "Pinch / Scroll": "Zoom" },
    href: "/games/vanguard-engine/",
  },
  helios: {
    id: "helios",
    title: "Helios Form",
    genre: "Futuristic Vehicle Systems Showroom",
    description: "Explore advanced sub-orbital and deep-space vessels in an orbital showroom with reflective staging, dynamic lighting, and vessel dossiers.",
    controls: { "Click / Arrows": "Select Vehicle", "Mouse Drag": "Orbit Inspect", "Scroll": "Zoom" },
    href: "/games/helios-engine/",
  },
  heliosEngine: {
    id: "heliosEngine",
    title: "Helios Form",
    genre: "Futuristic Vehicle Systems Showroom",
    description: "Explore advanced sub-orbital and deep-space vessels in an orbital showroom with reflective staging, dynamic lighting, and vessel dossiers.",
    controls: { "Click / Arrows": "Select Vehicle", "Mouse Drag": "Orbit Inspect", "Scroll": "Zoom" },
    href: "/games/helios-engine/",
  },
  ninjutsu: {
    id: "ninjutsu",
    title: "Ninjutsu",
    genre: "Augmented Reality Hand Sign Ninjutsu",
    description: "Perform authentic ninja hand signs via webcam to manifest Rasenshuriken, summon Chidori lightning, create shadow clones, and trigger log substitutions.",
    controls: { "Webcam / Hands": "Form Hand Signs", "Open Palm (Right)": "Rasenshuriken", "Open Palm (Left)": "Chidori", "Crossed Fingers": "Shadow Clones", "Steeple Tips": "Substitution" },
    href: "/games/ninjutsu-engine/",
  },
  ninjutsuEngine: {
    id: "ninjutsuEngine",
    title: "Ninjutsu",
    genre: "Augmented Reality Hand Sign Ninjutsu",
    description: "Perform authentic ninja hand signs via webcam to manifest Rasenshuriken, summon Chidori lightning, create shadow clones, and trigger log substitutions.",
    controls: { "Webcam / Hands": "Form Hand Signs", "Open Palm (Right)": "Rasenshuriken", "Open Palm (Left)": "Chidori", "Crossed Fingers": "Shadow Clones", "Steeple Tips": "Substitution" },
    href: "/games/ninjutsu-engine/",
  },
  soccer: {
    id: "soccer",
    title: "Final Whistle: Spain vs Argentina",
    genre: "Championship Soccer Simulator",
    description: "Lead Spain against Argentina in a high-stakes championship final with animated players, ball physics, and cheering stadium crowds.",
    controls: { "WASD / Arrows": "Move Player", "Space": "Shoot / Tackle", "E": "Pass" },
    href: "/games/soccer-engine/",
  },
  soccerEngine: {
    id: "soccerEngine",
    title: "Final Whistle: Spain vs Argentina",
    genre: "Championship Soccer Simulator",
    description: "Lead Spain against Argentina in a high-stakes championship final with animated players, ball physics, and cheering stadium crowds.",
    controls: { "WASD / Arrows": "Move Player", "Space": "Shoot / Tackle", "E": "Pass" },
    href: "/games/soccer-engine/",
  },
  putt: {
    id: "putt",
    title: "Genesis Grove Putt-Putt",
    genre: "18-Hole 3D Splat Mini-Golf",
    description: "An 18-hole putting round through California-inspired splat worlds with dynamic surface physics, ball trajectory, and hole layouts.",
    controls: { "Mouse Drag": "Aim & Stroke", "Space": "Charge Putt", "R": "Reset Ball" },
    href: "/games/putt-engine/",
  },
  puttEngine: {
    id: "puttEngine",
    title: "Genesis Grove Putt-Putt",
    genre: "18-Hole 3D Splat Mini-Golf",
    description: "An 18-hole putting round through California-inspired splat worlds with dynamic surface physics, ball trajectory, and hole layouts.",
    controls: { "Mouse Drag": "Aim & Stroke", "Space": "Charge Putt", "R": "Reset Ball" },
    href: "/games/putt-engine/",
  },
  pogo: {
    id: "pogo",
    title: "Pogo Man",
    genre: "Side-Scrolling Double Jump Arcade",
    description: "Bounce through bustling downtown city traffic with double jump timing, charge bounces, combos, and obstacles.",
    controls: { "Space / Click": "Jump / Double Jump", "Hold Space": "Charge High Bounce" },
    href: "/games/pogo-engine/",
  },
  pogoEngine: {
    id: "pogoEngine",
    title: "Pogo Man",
    genre: "Side-Scrolling Double Jump Arcade",
    description: "Bounce through bustling downtown city traffic with double jump timing, charge bounces, combos, and obstacles.",
    controls: { "Space / Click": "Jump / Double Jump", "Hold Space": "Charge High Bounce" },
    href: "/games/pogo-engine/",
  },
}


