import type * as THREE from "three"
import type {
  AudioGroup,
  AudioOptions,
  AudioSystem,
  MusicConfig,
  NoiseConfig,
  SoundFactory,
  SoundOutput,
  SoundPlayConfig,
  ToneConfig,
  Vector3Like,
} from "./types.ts"

declare global {
  interface Window {
    webkitAudioContext?: typeof AudioContext
  }
}

/**
 * Sound, synthesised. No files, no loading, no CDN.
 *
 * The sandbox has no audio assets and fetching them is a gamble on a url, so
 * every sound here is generated by the Web Audio API at the moment it plays.
 * That is not a compromise: oscillators and filtered noise are exactly what
 * arcade sound effects are, and they cost nothing and never fail to load.
 *
 * Browsers refuse to start audio before the player has interacted with the
 * page — an unavoidable rule, and the reason a game that "has no sound" usually
 * just never got a gesture. This unlocks itself on the first click, tap or key,
 * so a game never has to think about it.
 *
 *   const audio = createAudio()
 *   audio.play("coin")
 *   audio.tone({ frequency: 440, duration: 0.2 })
 */
export function createAudio(options: AudioOptions = {}): AudioSystem {
  const { volume = 0.35 } = options

  let context: AudioContext | null = null
  let master: GainNode | null = null
  let musicGain: GainNode | null = null
  let unlocked = false
  let currentVolume = volume
  let pitchShift = 1
  let activeDestination: AudioNode | null = null
  let activeGainMultiplier = 1
  const clips = new Map<string, AudioBuffer>()
  let activeBgmSource: AudioBufferSourceNode | null = null
  let activeBgmGain: GainNode | null = null

  const groupVolumes = new Map<AudioGroup, number>([
    ["master", volume],
    ["sfx", 1],
    ["ui", 0.8],
    ["ambience", 0.6],
    ["voice", 1],
    ["music", 0.5],
  ])
  const groupMuted = new Map<AudioGroup, boolean>()
  const groups = new Map<AudioGroup, GainNode>()
  const lastPlayed = new Map<string, number>()

  function ensure(): AudioContext | null {
    if (context) return context
    if (typeof window === "undefined") return null
    const Context = window.AudioContext ?? window.webkitAudioContext
    if (!Context) return null
    context = new Context()
    master = context.createGain()
    master.gain.value = currentVolume
    master.connect(context.destination)
    groups.set("master", master)

    for (const grp of ["sfx", "ui", "ambience", "voice", "music"] as const) {
      const g = context.createGain()
      const vol = groupMuted.get(grp) ? 0 : (groupVolumes.get(grp) ?? 1)
      g.gain.value = vol
      g.connect(master)
      groups.set(grp, g)
    }
    musicGain = groups.get("music")!
    return context
  }

  function unlock() {
    const ctx = ensure()
    if (!ctx) return
    if (ctx.state === "suspended") ctx.resume()
    unlocked = true
  }

  if (typeof window !== "undefined") {
    for (const event of ["pointerdown", "keydown", "touchstart"]) {
      window.addEventListener(event, unlock, { once: false, passive: true })
    }
  }

  function now(): number {
    return context ? context.currentTime : 0
  }

  /**
   * One note. `slide` bends the pitch over the note's life, which is the whole
   * difference between a beep and a jump, a laser or a power-up.
   */
  function tone(config: ToneConfig = {}): OscillatorNode | undefined {
    const ctx = ensure()
    if (!ctx || audio.muted || !master) return
    const {
      frequency = 440,
      type = "square",
      duration = 0.15,
      gain = 0.3,
      slide = 0,
      attack = 0.005,
      delay = 0,
      destination = activeDestination ?? (config.group ? groups.get(config.group) : null) ?? groups.get("sfx") ?? master,
    } = config

    const finalGain = gain * activeGainMultiplier
    const start = now() + delay
    const pitched = frequency * pitchShift
    const oscillator = ctx.createOscillator()
    const envelope = ctx.createGain()

    oscillator.type = type
    oscillator.frequency.setValueAtTime(pitched, start)
    if (slide) {
      oscillator.frequency.exponentialRampToValueAtTime(
        Math.max(1, pitched + slide * pitchShift),
        start + duration
      )
    }

    envelope.gain.setValueAtTime(0.0001, start)
    envelope.gain.exponentialRampToValueAtTime(Math.max(0.0001, finalGain), start + attack)
    envelope.gain.exponentialRampToValueAtTime(0.0001, start + duration)

    oscillator.connect(envelope)
    envelope.connect(destination)
    oscillator.start(start)
    oscillator.stop(start + duration + 0.02)
    return oscillator
  }

  /** Filtered white noise: explosions, footsteps, wind, hits, engine rumble. */
  function noise(config: NoiseConfig = {}): AudioBufferSourceNode | undefined {
    const ctx = ensure()
    if (!ctx || audio.muted || !master) return
    const {
      duration = 0.3,
      gain = 0.3,
      frequency = 1200,
      type = "lowpass",
      sweep = 0,
      Q = 1,
      delay = 0,
      destination = activeDestination ?? (config.group ? groups.get(config.group) : null) ?? groups.get("sfx") ?? master,
    } = config

    const finalGain = gain * activeGainMultiplier
    const start = now() + delay
    const frames = Math.max(1, Math.floor(ctx.sampleRate * duration))
    const buffer = ctx.createBuffer(1, frames, ctx.sampleRate)
    const data = buffer.getChannelData(0)
    for (let i = 0; i < frames; i++) data[i] = Math.random() * 2 - 1

    const source = ctx.createBufferSource()
    source.buffer = buffer

    const filter = ctx.createBiquadFilter()
    filter.type = type
    filter.frequency.setValueAtTime(frequency, start)
    filter.Q.value = Q
    if (sweep) {
      filter.frequency.exponentialRampToValueAtTime(
        Math.max(40, frequency + sweep),
        start + duration
      )
    }

    const envelope = ctx.createGain()
    envelope.gain.setValueAtTime(Math.max(0.0001, finalGain), start)
    envelope.gain.exponentialRampToValueAtTime(0.0001, start + duration)

    source.connect(filter)
    filter.connect(envelope)
    envelope.connect(destination)
    source.start(start)
    return source
  }

  /**
   * A named sound. These are the vocabulary most games need, tuned so they sit
   * together — nothing here is louder or brighter than the rest by accident.
   */
  const sounds: Record<string, SoundFactory> = {
    click: () =>
      tone({ frequency: 900, type: "square", duration: 0.04, gain: 0.14 }),
    blip: () =>
      tone({ frequency: 620, type: "square", duration: 0.07, gain: 0.2 }),
    select: () => {
      tone({ frequency: 520, duration: 0.06, gain: 0.18 })
      tone({ frequency: 780, duration: 0.08, gain: 0.18, delay: 0.05 })
    },
    coin: () => {
      tone({ frequency: 988, type: "square", duration: 0.07, gain: 0.22 })
      tone({
        frequency: 1319,
        type: "square",
        duration: 0.14,
        gain: 0.22,
        delay: 0.06,
      })
    },
    jump: () =>
      tone({
        frequency: 300,
        type: "square",
        duration: 0.16,
        gain: 0.22,
        slide: 420,
      }),
    land: () =>
      noise({ duration: 0.1, frequency: 500, gain: 0.18, sweep: -300 }),
    hit: () => {
      tone({
        frequency: 180,
        type: "sawtooth",
        duration: 0.12,
        gain: 0.28,
        slide: -120,
      })
      noise({ duration: 0.1, frequency: 2400, gain: 0.2, sweep: -1800 })
    },
    hurt: () =>
      tone({
        frequency: 420,
        type: "sawtooth",
        duration: 0.28,
        gain: 0.28,
        slide: -300,
      }),
    laser: () =>
      tone({
        frequency: 1400,
        type: "sawtooth",
        duration: 0.14,
        gain: 0.2,
        slide: -1100,
      }),
    shoot: () => {
      tone({
        frequency: 800,
        type: "square",
        duration: 0.06,
        gain: 0.16,
        slide: -500,
      })
      noise({ duration: 0.08, frequency: 3000, gain: 0.12, sweep: -2000 })
    },
    explosion: () => {
      noise({
        duration: 0.7,
        frequency: 900,
        gain: 0.4,
        sweep: -820,
        type: "lowpass",
      })
      tone({
        frequency: 90,
        type: "sine",
        duration: 0.5,
        gain: 0.3,
        slide: -60,
      })
    },
    powerup: () => {
      const steps = [523, 659, 784, 1047]
      steps.forEach((frequency, i) =>
        tone({
          frequency,
          type: "triangle",
          duration: 0.12,
          gain: 0.2,
          delay: i * 0.07,
        })
      )
    },
    win: () => {
      const fanfare = [523, 659, 784, 1047, 1319]
      fanfare.forEach((frequency, i) =>
        tone({
          frequency,
          type: "triangle",
          duration: 0.28,
          gain: 0.22,
          delay: i * 0.11,
        })
      )
    },
    lose: () => {
      const fall = [440, 370, 294, 220]
      fall.forEach((frequency, i) =>
        tone({
          frequency,
          type: "sawtooth",
          duration: 0.3,
          gain: 0.22,
          delay: i * 0.14,
        })
      )
    },
    step: () =>
      noise({ duration: 0.06, frequency: 900, gain: 0.08, sweep: -400 }),
    whoosh: () =>
      noise({
        duration: 0.3,
        frequency: 400,
        gain: 0.14,
        sweep: 1600,
        type: "bandpass",
        Q: 2,
      }),
    thud: () =>
      tone({
        frequency: 120,
        type: "sine",
        duration: 0.18,
        gain: 0.34,
        slide: -60,
      }),
    alarm: () => {
      tone({ frequency: 740, type: "square", duration: 0.18, gain: 0.2 })
      tone({
        frequency: 620,
        type: "square",
        duration: 0.18,
        gain: 0.2,
        delay: 0.2,
      })
    },
    hover: () =>
      tone({ frequency: 800, type: "sine", duration: 0.03, gain: 0.08 }),
    confirm: () => {
      tone({ frequency: 587, type: "sine", duration: 0.06, gain: 0.16 })
      tone({ frequency: 880, type: "triangle", duration: 0.09, gain: 0.18, delay: 0.05 })
    },
    cancel: () =>
      tone({ frequency: 494, type: "sawtooth", duration: 0.08, gain: 0.14, slide: -150 }),
    pause: () =>
      tone({ frequency: 392, type: "square", duration: 0.05, gain: 0.12 }),
    dash: () =>
      noise({ duration: 0.18, frequency: 800, gain: 0.22, sweep: 1400, type: "bandpass", Q: 3 }),
    boost: () => {
      tone({ frequency: 220, type: "sawtooth", duration: 0.28, gain: 0.24, slide: 440 })
      noise({ duration: 0.25, frequency: 1200, gain: 0.15, sweep: 800 })
    },
    drift: () =>
      noise({ duration: 0.22, frequency: 600, gain: 0.18, type: "bandpass", Q: 4 }),
    shield: () => {
      tone({ frequency: 784, type: "sine", duration: 0.25, gain: 0.24 })
      tone({ frequency: 1174, type: "triangle", duration: 0.2, gain: 0.2, delay: 0.04 })
    },
    score: () => {
      tone({ frequency: 1046, type: "square", duration: 0.08, gain: 0.18 })
      tone({ frequency: 1318, type: "triangle", duration: 0.12, gain: 0.2, delay: 0.06 })
    },
    checkpoint: () => {
      tone({ frequency: 523, duration: 0.14, gain: 0.2 })
      tone({ frequency: 659, duration: 0.14, gain: 0.2, delay: 0.08 })
      tone({ frequency: 784, duration: 0.24, gain: 0.24, delay: 0.16 })
    },
    warning: () => {
      tone({ frequency: 880, type: "sawtooth", duration: 0.12, gain: 0.22, slide: -180 })
      tone({
        frequency: 880,
        type: "sawtooth",
        duration: 0.12,
        gain: 0.22,
        slide: -180,
        delay: 0.14,
      })
    },
    impact: () => {
      tone({ frequency: 160, type: "sine", duration: 0.2, gain: 0.35, slide: -90 })
      noise({ duration: 0.08, frequency: 2800, gain: 0.25, sweep: -2000 })
    },
  }

  // --- Music ----------------------------------------------------------------

  let musicTimer: ReturnType<typeof setInterval> | null = null

  /**
   * A looping arpeggio over a chord progression. Not a soundtrack, but a bed
   * of sound underneath the game, which is most of what background music does.
   */
  function startMusic(config: MusicConfig = {}) {
    const {
      notes = [220, 277, 330, 440, 330, 277],
      tempo = 240,
      type = "triangle",
      gain = 0.08,
    } = config
    stopMusic()
    ensure()
    let step = 0
    const interval = 60000 / tempo
    musicTimer = setInterval(() => {
      if (audio.muted || !unlocked || !musicGain) return
      tone({
        frequency: notes[step % notes.length],
        type,
        duration: (interval / 1000) * 0.9,
        gain,
        destination: musicGain,
      })
      step++
    }, interval)
  }

  function stopMusic() {
    if (musicTimer) clearInterval(musicTimer)
    musicTimer = null
  }

  const audio: AudioSystem = {
    muted: false,
    tone,
    noise,
    sounds,

    /**
     * Plays a named sound or preloaded audio clip.
     *
     * `vary` is the one option worth using everywhere: repetition is what makes
     * a sound effect grating, and a 5% random pitch shift makes twenty coin
     * pickups feel lively instead of mechanical.
     */
    play(name: string, config: SoundPlayConfig = {}): SoundOutput {
      if (clips.has(name)) {
        return audio.playClip(name, {
          volume:
            typeof config.volume === "number"
              ? config.volume
              : typeof config.gain === "number"
                ? config.gain
                : 1,
          pitchVariance: config.vary,
          group: config.group,
        })
      }
      const sound = sounds[name]
      if (!sound) return
      unlock()
      const { pitch = 1, vary = 0 } = config
      pitchShift = pitch * (1 + (Math.random() - 0.5) * 2 * vary)
      const uiSounds = new Set(["click", "blip", "select", "hover", "confirm", "cancel", "pause"])
      const targetGroup = config.group ?? (uiSounds.has(name) ? "ui" : "sfx")
      activeDestination =
        (config.destination as AudioNode) ?? groups.get(targetGroup) ?? master
      activeGainMultiplier =
        typeof config.volume === "number"
          ? config.volume
          : typeof config.gain === "number"
            ? config.gain
            : 1
      try {
        return sound(config)
      } finally {
        pitchShift = 1
        activeDestination = null
        activeGainMultiplier = 1
      }
    },

    /** Registers a sound of your own, callable by name like the built-ins. */
    define(name: string, factory: SoundFactory): AudioSystem {
      sounds[name] = factory
      return audio
    },

    get volume(): number {
      return currentVolume
    },
    set volume(value: number) {
      currentVolume = value
      ensure()
      if (master && !audio.muted) master.gain.value = value
    },

    mute(value: boolean = true): AudioSystem {
      audio.muted = value
      if (master) master.gain.value = value ? 0 : currentVolume
      return audio
    },
    unmute(): AudioSystem {
      return audio.mute(false)
    },
    isMuted(): boolean {
      return audio.muted
    },
    toggleMute(): AudioSystem {
      return audio.mute(!audio.muted)
    },

    music: { start: startMusic, stop: stopMusic },

    async load(name: string, url: string): Promise<AudioBuffer | undefined> {
      return audio.loadClip(name, url)
    },

    async loadClip(name: string, url: string): Promise<AudioBuffer | undefined> {
      const ctx = ensure()
      if (!ctx) return undefined
      if (clips.has(name)) return clips.get(name)
      try {
        const response = await fetch(url)
        if (!response.ok) return undefined
        const arrayBuf = await response.arrayBuffer()
        const audioBuf = await ctx.decodeAudioData(arrayBuf)
        clips.set(name, audioBuf)
        return audioBuf
      } catch {
        return undefined
      }
    },

    playClip(
      name: string,
      options: { volume?: number; pitchVariance?: number; loop?: boolean; group?: AudioGroup } = {}
    ): AudioBufferSourceNode | undefined {
      const ctx = ensure()
      if (!ctx || audio.muted || !master) return undefined
      const buf = clips.get(name)
      if (!buf) return undefined
      unlock()
      const { volume = 1, pitchVariance = 0, loop = false, group = "sfx" } = options
      const source = ctx.createBufferSource()
      const gainNode = ctx.createGain()
      source.buffer = buf
      source.loop = loop
      if (pitchVariance > 0) {
        source.playbackRate.value = 1 + (Math.random() - 0.5) * pitchVariance * 2
      }
      gainNode.gain.value = volume
      const targetDest = groups.get(group) ?? master
      source.connect(gainNode).connect(targetDest)
      source.start()
      return source
    },

    playMusic(
      url: string,
      options: { volume?: number; loop?: boolean; fadeIn?: number } = {}
    ): void {
      const ctx = ensure()
      if (!ctx || !master) return
      unlock()
      const { volume = 0.5, loop = true, fadeIn = 0.5 } = options
      audio.stopMusic()
      void (async () => {
        try {
          const response = await fetch(url)
          if (!response.ok) return
          const audioBuf = await ctx.decodeAudioData(await response.arrayBuffer())
          const source = ctx.createBufferSource()
          const gainNode = ctx.createGain()
          source.buffer = audioBuf
          source.loop = loop
          const startTime = ctx.currentTime
          gainNode.gain.setValueAtTime(0.001, startTime)
          gainNode.gain.linearRampToValueAtTime(volume, startTime + fadeIn)
          const dest = groups.get("music") ?? master
          source.connect(gainNode).connect(dest)
          source.start()
          activeBgmSource = source
          activeBgmGain = gainNode
        } catch {}
      })()
    },

    stopMusic(fadeOut: number = 0.3): void {
      if (!activeBgmSource || !activeBgmGain || !context) return
      const curTime = context.currentTime
      activeBgmGain.gain.setValueAtTime(activeBgmGain.gain.value, curTime)
      activeBgmGain.gain.linearRampToValueAtTime(0.001, curTime + fadeOut)
      const src = activeBgmSource
      setTimeout(() => {
        try {
          src.stop()
        } catch {}
      }, fadeOut * 1000)
      activeBgmSource = null
      activeBgmGain = null
    },

    getGroupVolume(group: AudioGroup): number {
      return groupVolumes.get(group) ?? 1
    },
    setGroupVolume(group: AudioGroup, volume: number): void {
      const clamped = Math.max(0, Math.min(1, volume))
      groupVolumes.set(group, clamped)
      ensure()
      const node = groups.get(group)
      if (node && !groupMuted.get(group) && !audio.muted) {
        node.gain.value = clamped
      }
    },
    muteGroup(group: AudioGroup, muted = true): void {
      groupMuted.set(group, muted)
      ensure()
      const node = groups.get(group)
      if (node) {
        node.gain.value = muted ? 0 : (groupVolumes.get(group) ?? 1)
      }
    },
    isGroupMuted(group: AudioGroup): boolean {
      return groupMuted.get(group) ?? false
    },

    duck(factor = 0.5, durationSec = 0.3): void {
      const ctx = ensure()
      if (!ctx) return
      const cur = ctx.currentTime
      for (const name of ["music", "ambience"] as const) {
        const node = groups.get(name)
        if (!node) continue
        const base = groupMuted.get(name) ? 0 : (groupVolumes.get(name) ?? 1)
        node.gain.cancelScheduledValues(cur)
        node.gain.setValueAtTime(node.gain.value, cur)
        node.gain.linearRampToValueAtTime(base * factor, cur + 0.05)
        node.gain.setValueAtTime(base * factor, cur + Math.max(0.05, durationSec - 0.05))
        node.gain.linearRampToValueAtTime(base, cur + durationSec)
      }
    },

    playWithCooldown(
      name: string,
      cooldownMs = 100,
      config: SoundPlayConfig = {}
    ): SoundOutput {
      const t = typeof performance !== "undefined" ? performance.now() : Date.now()
      const last = lastPlayed.get(name) ?? -Infinity
      if (t - last < cooldownMs) return
      lastPlayed.set(name, t)
      return audio.play(name, config)
    },

    playAt(
      name: string,
      position: Vector3Like,
      listener?: Vector3Like | THREE.Camera,
      config: SoundPlayConfig & { maxDistance?: number } = {}
    ): SoundOutput {
      const { maxDistance = 30, ...restConfig } = config
      const ctx = ensure()
      if (!ctx || audio.muted || !master) return

      const sx = Array.isArray(position) ? position[0] : "x" in position ? position.x : 0
      const sy = Array.isArray(position) ? position[1] : "y" in position ? position.y : 0
      const sz = Array.isArray(position) ? position[2] : "z" in position ? position.z : 0

      let lx = 0
      let ly = 0
      let lz = 0
      let rightX = 1
      let rightZ = 0
      if (listener) {
        if ("isCamera" in (listener as object)) {
          const cam = listener as THREE.Camera
          lx = cam.position.x
          ly = cam.position.y
          lz = cam.position.z
          const el = cam.matrixWorld.elements
          rightX = el[0]
          rightZ = el[2]
        } else {
          lx = Array.isArray(listener) ? listener[0] : "x" in listener ? listener.x : 0
          ly = Array.isArray(listener) ? listener[1] : "y" in listener ? listener.y : 0
          lz = Array.isArray(listener) ? listener[2] : "z" in listener ? listener.z : 0
        }
      }

      const dx = sx - lx
      const dy = sy - ly
      const dz = sz - lz
      const dist = Math.sqrt(dx * dx + dy * dy + dz * dz)
      if (dist > maxDistance) return

      const dist01 = Math.max(0, 1 - dist / maxDistance)
      const volAtten = dist01 * dist01

      const normDist = dist > 0.001 ? dist : 1
      const pan = Math.max(-1, Math.min(1, (dx * rightX + dz * rightZ) / normDist))

      const spatialGain = ctx.createGain()
      spatialGain.gain.value = volAtten

      let outputNode: AudioNode = spatialGain
      const createPan = (ctx as unknown as { createStereoPanner?: () => StereoPannerNode })
        .createStereoPanner
      if (typeof createPan === "function") {
        const panner = createPan.call(ctx)
        panner.pan.value = pan
        spatialGain.connect(panner)
        outputNode = panner
      }

      const uiSounds = new Set(["click", "blip", "select", "hover", "confirm", "cancel", "pause"])
      const targetGroup = restConfig.group ?? (uiSounds.has(name) ? "ui" : "sfx")
      outputNode.connect(groups.get(targetGroup) ?? master)

      return audio.play(name, {
        ...restConfig,
        destination: spatialGain,
      })
    },

    get ready(): boolean {
      return unlocked
    },
    unlock,

    dispose() {
      stopMusic()
      audio.stopMusic()
      clips.clear()
      groups.clear()
      context?.close()
      context = null
    },
  }

  return audio
}
