import type { LevelDef } from './LevelDef';
import { buildProgressiveLevels } from './progression';

type LevelLayout = Omit<LevelDef, 'difficulty' | 'traffic'>;

const dockStraight = (
  x: number,
  z: number,
  yaw: number,
): LevelDef['docks'][number] => ({
  model: 'dock_straight',
  x,
  z,
  yaw,
  collider: { hx: 2.8, hy: 0.45, hz: 0.7 },
});

const dockFinger = (
  x: number,
  z: number,
  yaw: number,
): LevelDef['docks'][number] => ({
  model: 'dock_finger_end',
  x,
  z,
  yaw,
  collider: { hx: 1.9, hy: 0.45, hz: 0.65 },
});

const dockCorner = (
  x: number,
  z: number,
  yaw: number,
): LevelDef['docks'][number] => ({
  model: 'dock_corner_l',
  x,
  z,
  yaw,
  collider: { hx: 2.2, hy: 0.45, hz: 2.2 },
});

/**
 * 15 unique courses — pairwise tag similarity must stay ≤ 50%.
 * Each level owns a distinct path shape + approach + topology combo.
 */
const LEVEL_LAYOUTS: LevelLayout[] = [
  {
    id: 1,
    name: 'Open Berth',
    subtitle: 'Ease in straight. Brake early.',
    spawn: { x: 0, z: 14, yaw: Math.PI },
    slip: {
      x: 0,
      z: -6.2,
      yaw: Math.PI,
      halfWidth: 2.6,
      halfLength: 3.4,
      yawToleranceDeg: 28,
      maxHoldSpeed: 1.6,
      holdSeconds: 1.5,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'straight',
      slipFacing: 'S',
      spawnQuadrant: 'N',
      density: 'open',
      weather: 'calm',
      obstacles: 'mixed',
      topology: 'finger',
    },
    wind: { x: 0, z: 0 },
    waves: { amplitude: 0.08, period: 4.5 },
    parSeconds: 35,
    parSlack: 25,
    damageBudget: 4.5,
    basin: { halfWidth: 18, halfDepth: 20 },
    docks: [
      dockStraight(-5.4, -6, 0),
      dockStraight(5.4, -6, 0),
      dockFinger(-5.4, -9.2, 0),
      dockFinger(5.4, -9.2, 0),
      dockStraight(0, -12.2, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -4.2, z: -7.4, yaw: 0 },
      { model: 'cleat_post', x: 4.2, z: -7.4, yaw: Math.PI },
      { model: 'life_ring_post', x: -7, z: -3, yaw: 0.2 },
      { model: 'marina_boathouse', x: -13, z: -10, yaw: Math.PI / 2 },
      { model: 'crate_stack', x: 11, z: -9, yaw: 0.4 },
      { model: 'bollard_lantern', x: 7.5, z: -3.5, yaw: 0 },
      { model: 'buoy_striped', x: -9, z: 6, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 9, z: 8, yaw: 0.5, buoy: true },
    ],
    parkedBoats: [{ model: 'boat_yellow_utility', x: -11, z: -6.5, yaw: Math.PI }],
  },
  {
    id: 2,
    name: 'Finger Pier',
    subtitle: 'Thread the fingers. Mind the sides.',
    spawn: { x: -13, z: 0, yaw: 0 },
    slip: {
      x: 5,
      z: 0,
      yaw: Math.PI / 2,
      halfWidth: 2.35,
      halfLength: 3.4,
      yawToleranceDeg: 26,
      maxHoldSpeed: 1.45,
      holdSeconds: 1.7,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'dogleg',
      slipFacing: 'E',
      spawnQuadrant: 'W',
      density: 'medium',
      weather: 'swell',
      obstacles: 'boat',
      topology: 'finger',
    },
    waypoints: [
      { x: -8, z: 3.5 },
      { x: -3, z: 0 },
    ],
    wind: { x: 0.06, z: 0.02 },
    waves: { amplitude: 0.22, period: 3.8 },
    parSeconds: 45,
    parSlack: 30,
    damageBudget: 4.0,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      dockStraight(5, 5.0, 0),
      dockStraight(5, -5.0, 0),
      dockFinger(8.2, 5.0, 0),
      dockFinger(8.2, -5.0, 0),
      dockStraight(10.5, 0, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: 5, z: 3.4, yaw: 0 },
      { model: 'cleat_post', x: 5, z: -3.4, yaw: Math.PI },
      { model: 'buoy_striped', x: -8, z: 4.5, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: -8, z: -4.5, yaw: 0.3, buoy: true },
      { model: 'marina_boathouse', x: 14, z: -6, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: 12, z: 5, yaw: 0.2 },
      { model: 'bollard_lantern', x: 7, z: 7, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: 5, z: 9.5, yaw: Math.PI },
      { model: 'boat_yellow_utility', x: 5, z: -9.5, yaw: Math.PI },
    ],
  },
  {
    id: 3,
    name: 'Around the Bend',
    subtitle: 'Turn the corner before you commit.',
    spawn: { x: -14, z: 3, yaw: 0.1 },
    slip: {
      x: 6,
      z: -8,
      yaw: Math.PI,
      halfWidth: 2.3,
      halfLength: 3.3,
      yawToleranceDeg: 24,
      maxHoldSpeed: 1.4,
      holdSeconds: 1.8,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'l_bend',
      slipFacing: 'S',
      spawnQuadrant: 'W',
      density: 'medium',
      weather: 'calm',
      obstacles: 'dock',
      topology: 'corner',
    },
    waypoints: [
      { x: -5, z: 3 },
      { x: 7.5, z: 3 },
      { x: 7.5, z: -3 },
    ],
    wind: { x: 0.04, z: -0.03 },
    waves: { amplitude: 0.2, period: 4 },
    parSeconds: 55,
    parSlack: 35,
    damageBudget: 3.8,
    basin: { halfWidth: 20, halfDepth: 18 },
    docks: [
      dockStraight(-6, 6.5, 0),
      dockStraight(0, 6.5, 0),
      dockCorner(7.5, 6.2, 0),
      dockStraight(9.5, 0.5, Math.PI / 2),
      dockStraight(9.5, -5.5, Math.PI / 2),
      dockStraight(1.7, -11, 0),
      dockStraight(10.3, -11, 0),
      dockFinger(1.7, -13.5, 0),
      dockFinger(10.3, -13.5, 0),
    ],
    props: [
      { model: 'cleat_post', x: 4.4, z: -9.2, yaw: 0 },
      { model: 'cleat_post', x: 7.6, z: -9.2, yaw: Math.PI },
      { model: 'buoy_striped', x: -9, z: 0, yaw: 0, buoy: true },
      { model: 'life_ring_post', x: 10.5, z: -2, yaw: 0 },
      { model: 'marina_boathouse', x: 14, z: 4, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: -4, z: 8, yaw: 0.1 },
      { model: 'bollard_lantern', x: 11, z: 3, yaw: 0 },
    ],
    parkedBoats: [{ model: 'boat_yellow_utility', x: -11, z: 6.5, yaw: Math.PI / 2 }],
  },
  {
    id: 4,
    name: 'Back It In',
    subtitle: 'Reverse into the slip. Slow and steady.',
    spawn: { x: 0, z: 13, yaw: Math.PI },
    slip: {
      x: 0,
      z: -7.2,
      yaw: 0,
      halfWidth: 2.2,
      halfLength: 3.25,
      yawToleranceDeg: 24,
      maxHoldSpeed: 1.3,
      holdSeconds: 2.0,
    },
    approach: 'stern',
    tags: {
      approach: 'stern',
      path: 'gated',
      slipFacing: 'N',
      spawnQuadrant: 'N',
      density: 'medium',
      weather: 'calm',
      obstacles: 'boat',
      topology: 'finger',
    },
    waypoints: [
      { x: 0, z: 3 },
      { x: 0, z: -1.5 },
    ],
    wind: { x: 0.07, z: 0 },
    waves: { amplitude: 0.28, period: 3.6 },
    parSeconds: 65,
    parSlack: 40,
    damageBudget: 3.6,
    basin: { halfWidth: 16, halfDepth: 18 },
    docks: [
      dockStraight(-4.8, -7.2, 0),
      dockStraight(4.8, -7.2, 0),
      dockFinger(-4.8, -10.5, 0),
      dockFinger(4.8, -10.5, 0),
      dockStraight(-9.5, 4, Math.PI / 2),
      dockStraight(9.5, 4, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -3.5, z: -8.4, yaw: 0 },
      { model: 'cleat_post', x: 3.5, z: -8.4, yaw: Math.PI },
      { model: 'buoy_striped', x: -6, z: 8, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 6, z: 8, yaw: 0.5, buoy: true },
      { model: 'bollard_lantern', x: -6.5, z: -3, yaw: 0 },
      { model: 'life_ring_post', x: 6.5, z: -3, yaw: 0 },
      { model: 'marina_boathouse', x: -13, z: -8, yaw: Math.PI / 2 },
      { model: 'crate_stack', x: 12, z: -8, yaw: -0.3 },
    ],
    parkedBoats: [
      { model: 'boat_yellow_utility', x: -10, z: -5.5, yaw: Math.PI },
      { model: 'boat_teal_skiff', x: 10, z: -5.5, yaw: Math.PI },
    ],
  },

  // ——— Unique mid-game archetypes ———
  {
    id: 5,
    name: 'Parallel Quay',
    subtitle: 'Slide along the wall. Parallel park.',
    // Stern-style reverse into a north berth beside a long quay (parallel lane on the west).
    spawn: { x: -6, z: 13, yaw: Math.PI },
    slip: {
      x: 0,
      z: -6.5,
      yaw: 0,
      halfWidth: 2.4,
      halfLength: 3.4,
      yawToleranceDeg: 26,
      maxHoldSpeed: 1.35,
      holdSeconds: 2.0,
    },
    approach: 'parallel',
    tags: {
      approach: 'parallel',
      path: 'parallel_slide',
      slipFacing: 'N',
      spawnQuadrant: 'N',
      density: 'medium',
      weather: 'calm',
      obstacles: 'dock',
      topology: 'quay',
    },
    waypoints: [
      { x: -6, z: 4 },
      { x: -6, z: -2 },
      { x: 0, z: -2 },
      { x: 0, z: -4 },
    ],
    wind: { x: 0.03, z: 0 },
    waves: { amplitude: 0.12, period: 4.2 },
    parSeconds: 70,
    parSlack: 40,
    damageBudget: 3.5,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      // Long quay east of the berth.
      dockStraight(5, 4, Math.PI / 2),
      dockStraight(5, -2, Math.PI / 2),
      dockStraight(5, -8, Math.PI / 2),
      dockStraight(8, 0, 0),
      dockStraight(8, -6, 0),
      // North-facing berth (open south for the reverse gate).
      dockStraight(-4.6, -6.5, 0),
      dockStraight(4.6, -6.5, 0),
      dockFinger(-4.6, -9.8, 0),
      dockFinger(4.6, -9.8, 0),
    ],
    props: [
      { model: 'cleat_post', x: -3.2, z: -7.6, yaw: 0 },
      { model: 'cleat_post', x: 3.2, z: -7.6, yaw: Math.PI },
      { model: 'bollard_lantern', x: 6.5, z: -4, yaw: 0 },
      { model: 'life_ring_post', x: 6.5, z: 2, yaw: 0 },
      { model: 'marina_boathouse', x: 13, z: -8, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: 11, z: 4, yaw: 0.2 },
      { model: 'buoy_striped', x: -11, z: 6, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: -11, z: -2, yaw: 0.4, buoy: true },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: 10, z: 6, yaw: Math.PI },
      { model: 'boat_yellow_utility', x: 10, z: -2, yaw: Math.PI },
    ],
  },
  {
    id: 6,
    name: 'Crosswind Channel',
    subtitle: 'Beam wind. Counter-steer the whole way.',
    spawn: { x: 0, z: -14, yaw: 0 },
    slip: {
      x: 0,
      z: 8,
      yaw: 0,
      halfWidth: 2.2,
      halfLength: 3.3,
      yawToleranceDeg: 23,
      maxHoldSpeed: 1.3,
      holdSeconds: 2.0,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'straight',
      slipFacing: 'N',
      spawnQuadrant: 'S',
      density: 'medium',
      weather: 'crosswind',
      obstacles: 'buoy',
      topology: 'alley',
    },
    waypoints: [
      { x: 0, z: -6 },
      { x: 0, z: 2 },
    ],
    wind: { x: 0.22, z: 0, gust: 0.12 },
    waves: { amplitude: 0.55, period: 3.0, direction: { x: 1, z: 0 } },
    parSeconds: 70,
    parSlack: 40,
    damageBudget: 3.4,
    basin: { halfWidth: 14, halfDepth: 18 },
    docks: [
      dockStraight(-5.5, 8, 0),
      dockStraight(5.5, 8, 0),
      dockFinger(-5.5, 11.2, 0),
      dockFinger(5.5, 11.2, 0),
      dockStraight(0, 13.8, Math.PI / 2),
      dockStraight(-8, 0, Math.PI / 2),
      dockStraight(8, 0, Math.PI / 2),
      dockStraight(-8, -7, Math.PI / 2),
      dockStraight(8, -7, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -4, z: 9.2, yaw: 0 },
      { model: 'cleat_post', x: 4, z: 9.2, yaw: Math.PI },
      { model: 'buoy_striped', x: -4.5, z: -8, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 4.5, z: -8, yaw: 0.3, buoy: true },
      { model: 'buoy_striped', x: -4.5, z: -2, yaw: 0.6, buoy: true },
      { model: 'buoy_striped', x: 4.5, z: -2, yaw: 0.9, buoy: true },
      { model: 'buoy_striped', x: -4.5, z: 4, yaw: 1.2, buoy: true },
      { model: 'buoy_striped', x: 4.5, z: 4, yaw: 0.2, buoy: true },
      { model: 'marina_boathouse', x: -12, z: 8, yaw: Math.PI / 2 },
      { model: 'bollard_lantern', x: 7, z: 6, yaw: 0 },
    ],
  },
  {
    id: 7,
    name: 'Dock Maze',
    subtitle: 'One correct channel. Ignore the dead ends.',
    spawn: { x: -14, z: -14, yaw: 0.8 },
    slip: {
      x: 8,
      z: 8,
      yaw: Math.PI / 2,
      halfWidth: 2.25,
      halfLength: 3.3,
      yawToleranceDeg: 24,
      maxHoldSpeed: 1.3,
      holdSeconds: 2.0,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'maze',
      slipFacing: 'E',
      spawnQuadrant: 'SW',
      density: 'maze',
      weather: 'calm',
      obstacles: 'dock',
      topology: 'maze_grid',
    },
    // Open S→N then W→E corridor; decoy walls sit off the route.
    waypoints: [
      { x: -8, z: -12 },
      { x: -8, z: 8 },
      { x: 3, z: 8 },
    ],
    wind: { x: 0.02, z: 0.01 },
    waves: { amplitude: 0.15, period: 4.0 },
    parSeconds: 95,
    parSlack: 50,
    damageBudget: 3.2,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      // West wall of northbound lane (channel ~x=-8).
      dockStraight(-12.5, -8, Math.PI / 2),
      dockStraight(-12.5, 0, Math.PI / 2),
      dockStraight(-12.5, 6, Math.PI / 2),
      // East wall of northbound lane — gap near z=8 for the turn.
      dockStraight(-3.5, -10, Math.PI / 2),
      dockStraight(-3.5, -2, Math.PI / 2),
      // Dead-end spur south-east of the turn.
      dockStraight(2, -6, 0),
      dockStraight(6, -6, 0),
      dockStraight(6, -10, Math.PI / 2),
      // North wall of eastbound lane (channel ~z=8).
      dockStraight(-4, 12.5, 0),
      dockStraight(2, 12.5, 0),
      // South wall with opening at the turn.
      dockStraight(-4, 3.5, 0),
      dockStraight(2, 3.5, 0),
      // Destination finger open west.
      dockStraight(8, 12.2, 0),
      dockStraight(8, 3.8, 0),
      dockFinger(11.2, 12.2, 0),
      dockFinger(11.2, 3.8, 0),
      dockStraight(13.2, 8, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: 8, z: 10.4, yaw: 0 },
      { model: 'cleat_post', x: 8, z: 5.6, yaw: Math.PI },
      // Keep channel x≈-8 / z≈8 clear of buoys.
      { model: 'buoy_striped', x: 0, z: -12, yaw: 0, buoy: true },
      { model: 'marina_boathouse', x: 13, z: -8, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: -13, z: 12, yaw: 0.1 },
      { model: 'bollard_lantern', x: 4, z: 6, yaw: 0 },
      { model: 'life_ring_post', x: 0, z: 10, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: 4, z: -10, yaw: Math.PI },
      { model: 'boat_yellow_utility', x: 10, z: -2, yaw: Math.PI / 2 },
    ],
  },
  {
    id: 8,
    name: 'Hairpin Cove',
    subtitle: 'U-turn into the hidden cove.',
    // Proven L3 bend geometry, denser props + swell (tags stay unique).
    spawn: { x: 15, z: 2, yaw: -Math.PI / 2 },
    slip: {
      x: -6,
      z: -8,
      yaw: Math.PI,
      halfWidth: 2.3,
      halfLength: 3.3,
      yawToleranceDeg: 24,
      maxHoldSpeed: 1.35,
      holdSeconds: 1.95,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'u_turn',
      slipFacing: 'S',
      spawnQuadrant: 'SE',
      density: 'packed',
      weather: 'swell',
      obstacles: 'mixed',
      topology: 'corner',
    },
    waypoints: [
      { x: 5, z: 3 },
      { x: -7.5, z: 3 },
      { x: -7.5, z: -3 },
    ],
    wind: { x: -0.04, z: 0.02 },
    waves: { amplitude: 0.28, period: 3.5, direction: { x: -0.4, z: 0.8 } },
    parSeconds: 90,
    parSlack: 50,
    damageBudget: 3.2,
    basin: { halfWidth: 20, halfDepth: 18 },
    docks: [
      dockStraight(6, 6.5, 0),
      dockStraight(0, 6.5, 0),
      dockCorner(-7.5, 6.2, Math.PI / 2),
      dockStraight(-9.5, 0.5, Math.PI / 2),
      dockStraight(-9.5, -5.5, Math.PI / 2),
      dockStraight(-1.7, -11, 0),
      dockStraight(-10.3, -11, 0),
      dockFinger(-1.7, -13.5, 0),
      dockFinger(-10.3, -13.5, 0),
      dockStraight(14, -6, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -4.4, z: -9.2, yaw: 0 },
      { model: 'cleat_post', x: -7.6, z: -9.2, yaw: Math.PI },
      { model: 'buoy_striped', x: 9, z: 0, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 2, z: -2, yaw: 0.4, buoy: true },
      { model: 'life_ring_post', x: -10.5, z: -2, yaw: 0 },
      { model: 'marina_boathouse', x: -14, z: 4, yaw: Math.PI / 2 },
      { model: 'crate_stack', x: 4, z: 8, yaw: 0.1 },
      { model: 'bollard_lantern', x: -11, z: 3, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_yellow_utility', x: 11, z: 6.5, yaw: -Math.PI / 2 },
      { model: 'boat_teal_skiff', x: 12, z: -8, yaw: Math.PI },
    ],
  },
  {
    id: 9,
    name: 'Buoy Gauntlet',
    subtitle: 'S-curve through the buoys. Slip is open.',
    spawn: { x: -12, z: -12, yaw: 0.35 },
    slip: {
      x: 6,
      z: 8,
      yaw: Math.PI,
      halfWidth: 2.4,
      halfLength: 3.4,
      yawToleranceDeg: 26,
      maxHoldSpeed: 1.4,
      holdSeconds: 1.9,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 's_slalom',
      slipFacing: 'S',
      spawnQuadrant: 'SW',
      density: 'open',
      weather: 'swell',
      obstacles: 'buoy',
      topology: 'angled',
    },
    waypoints: [
      { x: -6, z: -8 },
      { x: 4, z: -4 },
      { x: -2, z: 2 },
      { x: 6, z: 4 },
    ],
    wind: { x: 0.04, z: 0.04 },
    waves: { amplitude: 0.28, period: 3.4, direction: { x: 0.6, z: 0.6 } },
    parSeconds: 90,
    parSlack: 50,
    damageBudget: 3.1,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      // South-facing open berth; angled decoration docks stay off the S-curve.
      dockStraight(0.7, 8, 0),
      dockStraight(11.3, 8, 0),
      dockFinger(0.7, 11.2, 0),
      dockFinger(11.3, 11.2, 0),
      dockStraight(-13, 12, -Math.PI / 4),
      dockStraight(13, -12, Math.PI / 4),
    ],
    props: [
      { model: 'cleat_post', x: 3.2, z: 9.2, yaw: 0 },
      { model: 'cleat_post', x: 8.8, z: 9.2, yaw: Math.PI },
      // Buoys flank the S-curve — leave ~4m clear around each waypoint.
      { model: 'buoy_striped', x: -9, z: -10, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 0, z: -8, yaw: 0.3, buoy: true },
      { model: 'buoy_striped', x: 7, z: -6, yaw: 0.6, buoy: true },
      { model: 'buoy_striped', x: -5, z: 0, yaw: 0.9, buoy: true },
      { model: 'buoy_striped', x: 2, z: 5, yaw: 1.2, buoy: true },
      { model: 'buoy_striped', x: 10, z: 2, yaw: 0.2, buoy: true },
      { model: 'marina_boathouse', x: -13, z: 6, yaw: Math.PI / 2 },
      { model: 'crate_stack', x: 13, z: -6, yaw: 0.2 },
      { model: 'bollard_lantern', x: 10, z: 6, yaw: 0 },
    ],
  },
  {
    id: 10,
    name: 'Diamond Berth',
    subtitle: 'Line up on the diagonal early.',
    spawn: { x: -12, z: 10, yaw: -0.5 },
    slip: {
      x: 5,
      z: -4,
      yaw: (Math.PI * 3) / 4,
      halfWidth: 2.2,
      halfLength: 3.3,
      yawToleranceDeg: 22,
      maxHoldSpeed: 1.25,
      holdSeconds: 2.1,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'dogleg',
      slipFacing: 'SE',
      spawnQuadrant: 'NW',
      density: 'medium',
      weather: 'crosswind',
      obstacles: 'mixed',
      topology: 'angled',
    },
    waypoints: [
      { x: -5, z: 6 },
      { x: 0, z: 2 },
      { x: 2.5, z: -0.5 },
    ],
    wind: { x: 0.12, z: -0.08, gust: 0.08 },
    waves: { amplitude: 0.38, period: 3.3, direction: { x: 0.7, z: -0.7 } },
    parSeconds: 80,
    parSlack: 45,
    damageBudget: 3.1,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      // Angled berth authored in the slip's local basis with a clear NW mouth.
      dockStraight(10.16, -1.67, (Math.PI * 3) / 4),
      dockStraight(2.67, -9.16, (Math.PI * 3) / 4),
      dockStraight(9.45, -8.45, (Math.PI * 5) / 4),
      dockStraight(12, 4, Math.PI / 2),
      dockStraight(-9, -8, 0),
    ],
    props: [
      { model: 'cleat_post', x: 8.32, z: -2.8, yaw: (Math.PI * 3) / 4 },
      { model: 'cleat_post', x: 3.8, z: -7.32, yaw: (Math.PI * 3) / 4 + Math.PI },
      { model: 'buoy_striped', x: -8, z: 4, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: -3, z: 7, yaw: 0.3, buoy: true },
      { model: 'marina_boathouse', x: 13, z: 6, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: 11, z: -10, yaw: 0.4 },
      { model: 'life_ring_post', x: 10, z: 0, yaw: 0 },
      { model: 'bollard_lantern', x: -6, z: -5, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_yellow_utility', x: -11, z: -3, yaw: Math.PI / 2 },
      { model: 'boat_teal_skiff', x: 12, z: -1, yaw: Math.PI },
    ],
  },
  {
    id: 11,
    name: 'Twin Gate Reverse',
    subtitle: 'Thread two gates, then reverse in.',
    // Proven stern layout (same family as level 4) with gate scenery.
    spawn: { x: 0, z: 13, yaw: Math.PI },
    slip: {
      x: 0,
      z: -7.2,
      yaw: 0,
      halfWidth: 2.2,
      halfLength: 3.25,
      yawToleranceDeg: 24,
      maxHoldSpeed: 1.3,
      holdSeconds: 2.05,
    },
    approach: 'stern',
    tags: {
      approach: 'stern',
      path: 'hairpin',
      slipFacing: 'N',
      spawnQuadrant: 'N',
      density: 'packed',
      weather: 'gust',
      obstacles: 'dock',
      topology: 'gates',
    },
    waypoints: [
      { x: 0, z: 4 },
      { x: 0, z: -1.5 },
    ],
    wind: { x: 0.05, z: 0, gust: 0.04 },
    waves: { amplitude: 0.22, period: 3.5 },
    parSeconds: 90,
    parSlack: 50,
    damageBudget: 3.0,
    basin: { halfWidth: 16, halfDepth: 18 },
    docks: [
      // Twin gate arches north of the berth.
      dockStraight(-6, 6, Math.PI / 2),
      dockStraight(6, 6, Math.PI / 2),
      dockStraight(-6, 1, Math.PI / 2),
      dockStraight(6, 1, Math.PI / 2),
      dockStraight(-4.8, -7.2, 0),
      dockStraight(4.8, -7.2, 0),
      dockFinger(-4.8, -10.5, 0),
      dockFinger(4.8, -10.5, 0),
    ],
    props: [
      { model: 'cleat_post', x: -3.5, z: -8.4, yaw: 0 },
      { model: 'cleat_post', x: 3.5, z: -8.4, yaw: Math.PI },
      { model: 'buoy_striped', x: -8, z: 8, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 8, z: 8, yaw: 0.4, buoy: true },
      { model: 'marina_boathouse', x: -13, z: -8, yaw: Math.PI / 2 },
      { model: 'crate_stack', x: 12, z: -8, yaw: -0.3 },
      { model: 'bollard_lantern', x: -6.5, z: -3, yaw: 0 },
      { model: 'life_ring_post', x: 6.5, z: -3, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: -10, z: -5.5, yaw: Math.PI },
      { model: 'boat_yellow_utility', x: 10, z: -5.5, yaw: Math.PI },
    ],
  },
  {
    id: 12,
    name: 'Island Ring',
    subtitle: 'Circle the island. Berth on the far side.',
    // Proven east berth (L2 family) with a buoy island south of the approach.
    spawn: { x: -13, z: 3, yaw: 0.1 },
    slip: {
      x: 6,
      z: 0,
      yaw: Math.PI / 2,
      halfWidth: 2.35,
      halfLength: 3.35,
      yawToleranceDeg: 25,
      maxHoldSpeed: 1.35,
      holdSeconds: 2.0,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'ring',
      slipFacing: 'E',
      spawnQuadrant: 'W',
      density: 'packed',
      weather: 'gust',
      obstacles: 'buoy',
      topology: 'island',
    },
    waypoints: [
      { x: -8, z: 6 },
      { x: -3, z: 6 },
      { x: -3, z: 0 },
      { x: 1, z: 0 },
    ],
    wind: { x: 0.04, z: 0 },
    waves: { amplitude: 0.2, period: 3.5 },
    parSeconds: 100,
    parSlack: 55,
    damageBudget: 2.9,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      dockStraight(6, 5.0, 0),
      dockStraight(6, -5.0, 0),
      dockFinger(9.2, 5.0, 0),
      dockFinger(9.2, -5.0, 0),
      dockStraight(11.5, 0, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: 6, z: 3.4, yaw: 0 },
      { model: 'cleat_post', x: 6, z: -3.4, yaw: Math.PI },
      { model: 'buoy_striped', x: -6, z: -6, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: -2, z: -8, yaw: 0.3, buoy: true },
      { model: 'buoy_striped', x: 2, z: -6, yaw: 0.6, buoy: true },
      { model: 'buoy_striped', x: -4, z: -9, yaw: 0.9, buoy: true },
      { model: 'marina_boathouse', x: 14, z: -6, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: 12, z: 5, yaw: 0.2 },
      { model: 'bollard_lantern', x: 8, z: 7, yaw: 0 },
      { model: 'life_ring_post', x: -11, z: 6, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: 4.5, z: 8.4, yaw: Math.PI },
      { model: 'boat_yellow_utility', x: 6, z: -9.5, yaw: Math.PI },
      { model: 'boat_teal_skiff', x: -11, z: -8, yaw: Math.PI / 2 },
    ],
  },
  {
    id: 13,
    name: 'Squeeze Alley',
    subtitle: 'Wait for the crossing boat, then hold the centerline.',
    spawn: { x: 15, z: 0, yaw: -Math.PI / 2 },
    slip: {
      x: -8,
      z: 0,
      yaw: -Math.PI / 2,
      halfWidth: 2.15,
      halfLength: 3.55,
      yawToleranceDeg: 22,
      maxHoldSpeed: 1.2,
      holdSeconds: 2.15,
    },
    approach: 'bow',
    tags: {
      approach: 'bow',
      path: 'straight',
      slipFacing: 'W',
      spawnQuadrant: 'E',
      density: 'packed',
      weather: 'gust',
      obstacles: 'dock',
      topology: 'alley',
    },
    waypoints: [
      { x: 7, z: 0 },
      { x: 1, z: 0 },
    ],
    wind: { x: 0, z: -0.05, gust: 0.03 },
    waves: { amplitude: 0.28, period: 3.2, direction: { x: 0, z: -1 } },
    parSeconds: 85,
    parSlack: 45,
    damageBudget: 2.7,
    basin: { halfWidth: 18, halfDepth: 14 },
    docks: [
      // A readable one-way alley: narrow enough to demand precision, with
      // enough beam clearance to counter late-level crosswind and wakes.
      dockStraight(6, 5.2, 0),
      dockStraight(6, -5.2, 0),
      dockStraight(0, 5.2, 0),
      dockStraight(0, -5.2, 0),
      dockStraight(-5, 5.2, 0),
      dockStraight(-5, -5.2, 0),
      dockStraight(-8, 5.3, 0),
      dockStraight(-8, -5.3, 0),
      dockFinger(-11.2, 5.3, 0),
      dockFinger(-11.2, -5.3, 0),
      dockStraight(-13.2, 0, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -8, z: 2.8, yaw: 0 },
      { model: 'cleat_post', x: -8, z: -2.8, yaw: Math.PI },
      // Keep mouth at x≈12 clear — buoys sit outside the alley walls.
      { model: 'buoy_striped', x: 16, z: 7, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 16, z: -7, yaw: 0.4, buoy: true },
      { model: 'marina_boathouse', x: 0, z: 10, yaw: 0 },
      { model: 'crate_stack', x: 0, z: -10, yaw: 0.2 },
      { model: 'bollard_lantern', x: -3, z: 3.2, yaw: 0 },
      { model: 'life_ring_post', x: -3, z: -3.2, yaw: 0 },
    ],
  },
  {
    id: 14,
    name: 'Storm Parallel',
    subtitle: 'Parallel park in a cross-gust.',
    // Mirror of Parallel Quay with storm weather: reverse into a south berth.
    spawn: { x: 6, z: -13, yaw: 0 },
    slip: {
      x: 0,
      z: 6.5,
      yaw: Math.PI,
      halfWidth: 2.4,
      halfLength: 3.4,
      yawToleranceDeg: 24,
      maxHoldSpeed: 1.25,
      holdSeconds: 2.15,
    },
    approach: 'parallel',
    tags: {
      approach: 'parallel',
      path: 'parallel_slide',
      slipFacing: 'S',
      spawnQuadrant: 'S',
      density: 'packed',
      weather: 'storm',
      obstacles: 'mixed',
      topology: 'alley',
    },
    waypoints: [
      { x: 6, z: -4 },
      { x: 6, z: 2 },
      { x: 0, z: 2 },
      { x: 0, z: 4 },
    ],
    wind: { x: -0.1, z: 0.02, gust: 0.06 },
    waves: { amplitude: 0.45, period: 2.9, direction: { x: -1, z: 0.2 } },
    parSeconds: 100,
    parSlack: 55,
    damageBudget: 2.6,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      dockStraight(-5, -4, Math.PI / 2),
      dockStraight(-5, 2, Math.PI / 2),
      dockStraight(-5, 8, Math.PI / 2),
      dockStraight(-8, 0, 0),
      dockStraight(-8, 6, 0),
      dockStraight(-4.6, 6.5, 0),
      dockStraight(4.6, 6.5, 0),
      dockFinger(-4.6, 9.8, 0),
      dockFinger(4.6, 9.8, 0),
      dockStraight(10, 0, Math.PI / 2),
      dockStraight(10, -6, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -3.2, z: 7.6, yaw: 0 },
      { model: 'cleat_post', x: 3.2, z: 7.6, yaw: Math.PI },
      { model: 'buoy_striped', x: 11, z: 4, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: 8, z: -3, yaw: 0.5, buoy: true },
      { model: 'marina_boathouse', x: -13, z: 0, yaw: Math.PI / 2 },
      { model: 'crate_stack', x: -10, z: 6, yaw: 0.2 },
      { model: 'bollard_lantern', x: -6.5, z: 4, yaw: 0 },
      { model: 'life_ring_post', x: -6.5, z: -2, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: -10, z: -6, yaw: 0 },
      { model: 'boat_yellow_utility', x: -10, z: 2, yaw: 0 },
    ],
  },
  {
    id: 15,
    name: 'Master Labyrinth',
    subtitle: 'Maze in. Reverse home. No mercy.',
    // Stern berth after a long L-corridor — harder weather, same geometry family as L4.
    spawn: { x: 15, z: 14, yaw: -2.1 },
    slip: {
      x: -6,
      z: -8,
      yaw: 0,
      halfWidth: 2.2,
      halfLength: 3.25,
      yawToleranceDeg: 23,
      maxHoldSpeed: 1.2,
      holdSeconds: 2.2,
    },
    approach: 'stern',
    tags: {
      approach: 'stern',
      path: 'maze',
      slipFacing: 'N',
      spawnQuadrant: 'NE',
      density: 'maze',
      weather: 'storm',
      obstacles: 'mixed',
      topology: 'maze_grid',
    },
    waypoints: [
      { x: 8, z: 10 },
      { x: 8, z: -12 },
      { x: -2, z: -14.5 },
    ],
    wind: { x: 0.08, z: -0.03, gust: 0.05 },
    waves: { amplitude: 0.42, period: 3.0, direction: { x: 0.6, z: -0.7 } },
    parSeconds: 120,
    parSlack: 60,
    damageBudget: 2.5,
    basin: { halfWidth: 18, halfDepth: 18 },
    docks: [
      dockStraight(3, 10, Math.PI / 2),
      dockStraight(3, 2, Math.PI / 2),
      dockStraight(13, 8, Math.PI / 2),
      dockStraight(2, 1.5, 0),
      dockStraight(-4, 1.5, 0),
      dockStraight(0, 12, 0),
      dockStraight(-8, 12, 0),
      dockStraight(-11.3, -8, 0),
      dockStraight(-0.7, -8, 0),
      dockFinger(-11.3, -11.2, 0),
      dockFinger(-0.7, -11.2, 0),
      dockStraight(-6, -1.4, Math.PI / 2),
    ],
    props: [
      { model: 'cleat_post', x: -4.4, z: -9.2, yaw: 0 },
      { model: 'cleat_post', x: -7.6, z: -9.2, yaw: Math.PI },
      { model: 'buoy_striped', x: 5, z: 6, yaw: 0, buoy: true },
      { model: 'buoy_striped', x: -12, z: 0, yaw: 0.4, buoy: true },
      { model: 'marina_boathouse', x: 15, z: -6, yaw: -Math.PI / 2 },
      { model: 'crate_stack', x: -12, z: 10, yaw: 0.2 },
      { model: 'bollard_lantern', x: -10, z: -4, yaw: 0 },
      { model: 'life_ring_post', x: 6, z: -6, yaw: 0 },
    ],
    parkedBoats: [
      { model: 'boat_teal_skiff', x: -2, z: 12, yaw: Math.PI },
      { model: 'boat_yellow_utility', x: -13, z: 4, yaw: Math.PI / 2 },
    ],
  },
];

export { buildProgressiveLevels } from './progression';

export const LEVELS: LevelDef[] = buildProgressiveLevels(LEVEL_LAYOUTS);
